### ISSUE TITLE
Export to JSON

### ISSUE THREAD

**Issue by pieterbergmans** [risparfinance/camus#8]
I tried exporting the results to JSON using results.export('json') but it didn't work.  Is this feature supported?  I see that it's part of the Record library so I assumed it would work.

**Comment by izidorome** [comment]
Hello @pieterbergmans ,
In fact, this is a missing feature from this library.

However, you can still convert the dictionary into JSON by using the built-in json module. 
Here is an example of how you can do this:

```python
import json
import camus

# Establish connection ....

rows = db.query("SELECT * FROM users")
json_data = json.dumps(rows.as_dict())
```


Hope that helps!
